version: '3.9'

services:
  test_db:
    image: postgres:14
    container_name: test_db
    ports:
      - '5439:5432'
    env_file:
      - .env
    networks:
      - test_net
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./data:/var/lib/postgresql/data



networks:
  test_net:
    external: false